
=head1 RETURN VALUES

B<KlelCompile> returns a pointer to a B<KLEL_CONTEXT> structure or
NULL indicating that no context could be created.  To determine if any
errors occurred, the pointer (whether it's NULL or not) should be
passed to and evaluated by B<KlelIsValid>.

B<KlelExecute> returns a pointer to a B<KLEL_VALUE> structure or NULL
indicating a failure.  If the call failed, the error that occurred can
be retrieved using B<KlelGetError>.  The value returned by
B<KlelExecute> should be freed using B<KlelFreeResult> once it's no
longer needed.

B<KlelIsValid> returns nonzero (i.e., true) if the specified
B<KLEL_CONTEXT> structure represents a valid expression (i.e., the
expression compiled without errors) and zero (i.e., false) otherwise.

B<KlelGetError> returns the last error or NULL if there are no errors.
Also note that the string returned by this function should not be
freed since that resource is managed by the implementation.

All other functions return a pointer to a result on success or NULL
indicating a failure.  The programmer is responsible for freeing the
values returned by these functions.

